version: 2.1
parameters:
  project-folder:
    type: string
    default: "marcosgimeno.com"
  temp-upload-folder-slug:
    type: string
    default: "-temp-upload"
  server-base-folder:
    type: string
    default: "/home/$SSH_USER/apps/"
  build-dist-folder:
    type: string
    default: "dist"
orbs:
  node: circleci/node@5
jobs:
  deploy:
    executor: node/default
    working_directory: ~/<< pipeline.parameters.project-folder >>
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:URTfidP7xVnBRdhWO03zsI0UdDd1nk+ht5pqT1f4UcY"
      - run:
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
            ssh $SSH_USER@$SSH_HOST "rm -dRf << pipeline.parameters.server-base-folder >><< pipeline.parameters.project-folder >><< pipeline.parameters.temp-upload-folder-slug >>"
            ssh $SSH_USER@$SSH_HOST "mkdir -p << pipeline.parameters.server-base-folder >><< pipeline.parameters.project-folder >><< pipeline.parameters.temp-upload-folder-slug >>"
            zip -r << pipeline.parameters.build-dist-folder >>.zip ./<< pipeline.parameters.build-dist-folder >>
            scp -v << pipeline.parameters.build-dist-folder >>.zip $SSH_USER@$SSH_HOST:/<< pipeline.parameters.server-base-folder >><< pipeline.parameters.project-folder >><< pipeline.parameters.temp-upload-folder-slug >>
            ssh $SSH_USER@$SSH_HOST "unzip -d << pipeline.parameters.server-base-folder >><< pipeline.parameters.project-folder >><< pipeline.parameters.temp-upload-folder-slug >> << pipeline.parameters.server-base-folder >><< pipeline.parameters.project-folder >><< pipeline.parameters.temp-upload-folder-slug >>/<< pipeline.parameters.build-dist-folder >>.zip"
            ssh $SSH_USER@$SSH_HOST "rm -dRf << pipeline.parameters.server-base-folder >><< pipeline.parameters.project-folder >>"
            ssh $SSH_USER@$SSH_HOST "mv << pipeline.parameters.server-base-folder >><< pipeline.parameters.project-folder >><< pipeline.parameters.temp-upload-folder-slug >>/<< pipeline.parameters.build-dist-folder >> << pipeline.parameters.server-base-folder >><< pipeline.parameters.project-folder >>"
            ssh $SSH_USER@$SSH_HOST "rm -dRf << pipeline.parameters.server-base-folder >><< pipeline.parameters.project-folder >><< pipeline.parameters.temp-upload-folder-slug >>"
workflows:
  deploy:
    jobs:
      - deploy
